#!/bin/bash

existing=$(who | grep $1 | cut -d" " -f1)
search="ssh $1@localhost"
pid=$(ps -ef | grep "$search" | grep -v "grep" | cut -d" " -f8)

if [ -z $existing ]
then
	echo "User is not logged or does not exist"
else
	$(sudo userdel -fr $1)
	$(kill $pid)
	echo "User has been deleted"
fi
