#!/bin/bash

existing=$(who | grep $1 | cut -d" " -f1)
pid=$(ps -ef | grep "ssh" | grep $1 | awk '{print $2}')
echo "pid = $pid"
if [ -z $existing ]
then
	echo "User is not logged or does not exist"
else
	$(sudo userdel -fr $1)
	$(sudo kill $pid)
	echo "User has been deleted"
fi
