#!/bin/bash

read input
existing=$(who | grep $input | cut -d" " -f6)
search="ssh $input@localghost"
pid=$(ps -ef | grep "$search" | grep -v "grep" | cut -d" " -f6)

if [ -z $existing ]
then
	echo "User is not logged or does not exist"
else
	$(userdel -fr $input)
	$(kill $pid)
	echo "User has been deleted"
fi
