#!/bin/bash
clear
echo "Entrer la taille de la suite de a deviner :"
read len

phrase=''
index=1
while [ "$index" -le $len ]
do
	n=$RANDOM
	let "n %= 9"
	phrase="${phrase}${n}"	
	let "index += 1"
done
clear
t1=$(date +%s)
echo "$phrase"
echo "Press ENTER to continu"
t2=$(date +%s)
read no
clear
echo "Answer : "
read answer
if [ $answer == $phrase ]
then
	spended=$(expr $t2 - $t1)
	echo "Congrat ! -> ${answer}, memorisation time : ${spended} seconds"
else
	echo "Wrong answer ! -> ${phrase}"
fi
